# Generated by Django 2.0.3 on 2018-05-24 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0007_auto_20180523_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='accident',
            old_name='tag',
            new_name='tag_var',
        ),
        migrations.AddField(
            model_name='accident',
            name='causes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='accident',
            name='step',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accident.Users'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accident.Status'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accident.System'),
        ),
        migrations.AlterField(
            model_name='events',
            name='accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accident.Accident'),
        ),
        migrations.AddField(
            model_name='tag',
            name='accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accident.Accident'),
        ),
    ]
