# Generated by Django 2.0.3 on 2018-05-25 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0015_auto_20180525_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accident.Users'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='causes',
            field=models.TextField(blank=True, null=True, verbose_name='Влияние'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accident.Source', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accident.Status'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accident.System', verbose_name='Система'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='text',
            field=models.TextField(verbose_name='Описание аварии'),
        ),
        migrations.AlterField(
            model_name='events',
            name='accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accident.Accident'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event',
            field=models.TextField(verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accident.Accident'),
        ),
    ]
