# Generated by Django 2.0.3 on 2018-08-07 13:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0025_auto_20180529_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusHist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accident.Status')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='isstatus_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='istag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accident.Tag'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accident.Status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accident.System', verbose_name='Система'),
        ),
        migrations.AlterField(
            model_name='events',
            name='accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accident.Accident', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='tag',
            name='accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accident.Accident'),
        ),
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accident.StatusHist'),
        ),
    ]
